version: '3.8'

services:
  db:
    container_name: management-db
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ofc
      MYSQL_USER: ofc
      MYSQL_PASSWORD: ofc
    ports:
      - "3307:3306"