version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ofc
      MYSQL_USER: ofc
      MYSQL_PASSWORD: ofc
    ports:
      - "3306:3306"
    volumes:
        - ./createTables.sql:/docker-entrypoint-initdb.d/createTables.sql